name: lambda-tf
on:
  push:
    branches: [ main ]
jobs:
  push-artifact:
    runs-on: ubuntu-latest 
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Create Zip
      run: |-
        ls -al && pwd
        zip -r code.zip ./

    - name: Push Zip to S3
      uses: shallwefootball/s3-upload-action@master
      with:
        aws_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_bucket: 'my-github-actions-bucket'
        source_dir: './'
        destination_dir: 'lambda'

    - name: AWS Lambda Deploy
      uses: appleboy/lambda-action@master
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: "us-east-1"
        function_name: My_Lambda_function
        zip_file: code.zip
        dry_run: true