name: lambda-tf
on:
  push:
    branches: [ main ]
jobs:
  push-artifact:
    runs-on: ubuntu-latest 
    steps:

    - name: Make artifact directory
      run: mkdir -p ./artifacts/${{ github.repository }}

    - name: Create Zip File
      uses: montudor/action-zip@v0.1.0
      with:
        args: zip -r ./artifacts/${{ github.repository }}/${{ github.sha }}.zip ./src

    - name: Push Zip to S3
      uses: shallwefootball/s3-upload-action@master
      with:
        aws_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_bucket: 'my-bucket2q34w5et4hrgfds'
        source_dir: './artifacts'